### ISSUE TITLE
Error Type 'invalid-json'

### ISSUE THREAD

**Issue by algo-coder** [steemscript/steemconnect#355]
Hi ! This is my first issue on Github, so forgive me if I don't follow the best practises.

Call to the steemconnect API used (vote operation)

`sc2.vote(voter, author, permlink, weight, function (err, res) {})`

From time to time (and often in a grouped way, like there's a more general problem behind it), I'm receiving this error in the callback.

`{ FetchError: invalid json response body at https://steemconnect.com/api/broadcast reason: Unexpected token < in JSON at position 0
    at /var/www/html/share2steem/node_modules/steemconnect/node_modules/node-fetch/lib/index.js:254:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at https://steemconnect.com/api/broadcast reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }`

When this error is received, this comes through the 'err' callback. I can't seem to figure where it comes from as it's doing it with all types of operations - votes but also comments - (and as I said, often happens for all ops in short windows of time). Problem is some other functions depend on the success of this call, and getting this response doesn't mean the operation hasn't been broadcast.

So you have this throwing an error, triggering the 'err' callback, despite the fact that the operation might (sometimes not) has been successful.

I'm not able to find any information on this anywhere.
Is it a known error ? Where does the problem come from ?

Thanks in advance for any information / help I might receive on this matter

**Comment by bonustrack** [comment]
Do you still having this issue @algo-coder ? I believe this issue appear if steemconnect API server go down.

**Comment by bonustrack** [comment]
Closing due to inactivity. If you're still having issues please open another issue.
